# Generated by Django 5.0.6 on 2024-05-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseFinderApp', '0002_user_details_dp_alter_user_details_product_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='product_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
