# Generated by Django 5.0.6 on 2024-05-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseFinderApp', '0003_user_details_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='product_contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
