# Generated by Django 5.0.6 on 2024-05-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseFinderApp', '0004_alter_user_details_product_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='product_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
