# Generated by Django 5.0.6 on 2024-05-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseFinderApp', '0005_alter_user_details_product_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
